# Generated by Django 5.2 on 2025-07-04 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('real', 'Realitäts-Layer'), ('cyber', 'Cyber-Layer')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('essence', models.CharField(blank=True, max_length=200)),
                ('player_action', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cyber_layer', models.ForeignKey(limit_choices_to={'type': 'cyber'}, on_delete=django.db.models.deletion.PROTECT, related_name='cyber_layer_progress', to='layers.layer')),
                ('real_layer', models.ForeignKey(limit_choices_to={'type': 'real'}, on_delete=django.db.models.deletion.PROTECT, related_name='real_layer_progress', to='layers.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
