# Generated by Django 5.2 on 2025-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Optional avatar image or generated artwork URL', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address for contact or recovery', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Current level based on experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ultra_name',
            field=models.CharField(blank=True, help_text='In-game character name chosen by the user', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Total experience points of the user'),
        ),
    ]
