# Generated by Django 5.2 on 2025-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_url_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cyber_layer',
            field=models.CharField(choices=[('SurfaceWebLayer', 'SurfaceWebLayer'), ('DeepNetLayer', 'DeepNetLayer'), ('DarkCodeLayer', 'DarkCodeLayer'), ('SyntheticLayer', 'SyntheticLayer'), ('VOIDLayer', 'VOIDLayer')], default='SurfaceWebLayer', help_text='Current Cyber-Layer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='real_layer',
            field=models.CharField(choices=[('BaseLayer', 'BaseLayer'), ('EmotionLayer', 'EmotionLayer'), ('FlowLayer', 'FlowLayer'), ('CoreLayer', 'CoreLayer'), ('UltraLayer', 'UltraLayer')], default='BaseLayer', help_text='Current Realitäts-Layer', max_length=20),
        ),
    ]
