# Generated by Django 5.2 on 2025-07-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
        ('origins', '0001_initial'),
        ('users', '0003_user_cyber_layer_user_real_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Individuelle Ultra-Bio des Users', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faction',
            field=models.ForeignKey(blank=True, help_text='Gewählte Fraktion des Users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='factions.faction'),
        ),
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Herkunft des Users (Ort, Land, Planet, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='origins.origin'),
        ),
    ]
