# Generated by Django 5.2 on 2025-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(blank=True, help_text='Optionaler Style/Theme-Name', max_length=50, null=True)),
                ('icon', models.URLField(blank=True, help_text='Optionales Icon (URL)', null=True)),
            ],
        ),
    ]
