version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: igoultra_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ultradev2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn ultrabackend.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Optional: Redis for caching and Celery (if needed later)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume: 