# Generated by Django 5.2 on 2025-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, help_text='z.B. Ort, Land, Planet, etc.', max_length=50, null=True)),
            ],
        ),
    ]
