# Generated by Django 5.2 on 2025-06-20 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_seasonxp_options_season_layer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasonxp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='season',
            name='layer_type',
        ),
        migrations.AddField(
            model_name='seasonxp',
            name='layer_type',
            field=models.CharField(choices=[('Real-Life', 'Real-Life'), ('Cyber', 'Cyber'), ('Game', 'Game')], default='Real-Life', help_text='Layer, für den diese XP gelten', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seasonxp',
            unique_together={('season', 'user', 'layer_type')},
        ),
    ]
