# Generated by Django 5.2 on 2025-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_seasonxp_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonxp',
            name='layer_type',
            field=models.CharField(choices=[('Real-Life', 'Real-Life'), ('Cyber', 'Cyber'), ('Game', 'Game')], default='Real-Life', help_text='Layer, für den diese XP gelten', max_length=20),
        ),
    ]
