# Generated by Django 5.2 on 2025-06-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0002_alter_seasonxp_options_season_layer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerRankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField()),
                ('layer_type', models.CharField(choices=[('Real-Life', 'Real-Life'), ('Cyber', 'Cyber'), ('Game', 'Game')], default='Real-Life', help_text='Layer, für den dieses Ranking gilt', max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp'],
                'unique_together': {('season', 'user', 'layer_type')},
            },
        ),
    ]
