# Generated by Django 5.2 on 2025-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layerrankingentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='layerrankingentry',
            name='cyber_layer',
            field=models.CharField(choices=[('SurfaceWebLayer', 'SurfaceWebLayer'), ('DeepNetLayer', 'DeepNetLayer'), ('DarkCodeLayer', 'DarkCodeLayer'), ('SyntheticLayer', 'SyntheticLayer'), ('VOIDLayer', 'VOIDLayer')], default='SurfaceWebLayer', help_text='Snapshot Cyber-Layer am Season-Ende', max_length=20),
        ),
        migrations.AddField(
            model_name='layerrankingentry',
            name='real_layer',
            field=models.CharField(choices=[('BaseLayer', 'BaseLayer'), ('EmotionLayer', 'EmotionLayer'), ('FlowLayer', 'FlowLayer'), ('CoreLayer', 'CoreLayer'), ('UltraLayer', 'UltraLayer')], default='BaseLayer', help_text='Snapshot Realitäts-Layer am Season-Ende', max_length=20),
        ),
        migrations.RemoveField(
            model_name='layerrankingentry',
            name='layer',
        ),
    ]
