# Generated by Django 5.2 on 2025-06-07 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('xp_amount', models.FloatField(help_text='XP pro Einheit (z. B. 5 XP/Repetition oder 2 XP/Minute)')),
                ('unit', models.CharField(help_text='z. B. "repetition", "time_minute", "step"', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positiv = Gain, Negativ = Abzug')),
                ('source', models.CharField(help_text='Identifier, z. B. "pushups", "running"', max_length=50)),
                ('metadata', models.JSONField(blank=True, help_text='z. B. {"unit":"time_minute","raw":"15 Minuten Yoga"}', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
