# Generated by Django 5.2 on 2025-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpevent',
            name='layer_type',
            field=models.CharField(choices=[('Real-Life', 'Real-Life'), ('Cyber', 'Cyber'), ('Game', 'Game')], default='Real-Life', help_text='Layer, aus dem dieses XP-Event stammt', max_length=20),
        ),
    ]
