# Generated by Django 5.2 on 2025-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0002_xpevent_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xptype',
            name='xp_type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Mental', 'Mental'), ('Cyber', 'Cyber'), ('Ultra', 'Ultra')], default='Physical', help_text='XP-Typ für Skills-System', max_length=20),
        ),
    ]
