"""
Django settings for ultrabackend project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables from .env file
load_dotenv()

# --------------------------------------------
# 📁 Base Directory Setup
# --------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------
# 🔐 Secret Key & Debug Mode
# --------------------------------------------
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# --------------------------------------------
# 🌍 Allowed Hosts
# --------------------------------------------
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "api.igoultra.de",
    ".herokuapp.com",
    "igoultra-backend-d20b10508b97.herokuapp.com",
]

# --------------------------------------------
# 🔑 Site Framework
# --------------------------------------------
SITE_ID = 1

# --------------------------------------------
# 🧩 Installed Applications
# --------------------------------------------
INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # 3rd-party auth & REST
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rest_framework",
    "rest_framework.authtoken",

    # Utilities
    "corsheaders",
    "django_extensions",
    "whitenoise.runserver_nostatic",

    # Local apps
    "users",
    "xp",
    "seasons",
]

# --------------------------------------------
# 🧱 Middleware Stack
# --------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "users.middleware.EnsureProfileComplete",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# --------------------------------------------
# 🔗 URL and WSGI Settings
# --------------------------------------------
ROOT_URLCONF = "ultrabackend.urls"
WSGI_APPLICATION = "ultrabackend.wsgi.application"

# --------------------------------------------
# 🎨 Templates Configuration
# --------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # Add custom template dirs here if needed
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --------------------------------------------
# 🛢️ PostgreSQL Database Configuration
# --------------------------------------------
raw_url = os.getenv("DATABASE_URL_LOCAL") or os.getenv("DATABASE_URL")
clean_url = raw_url.encode("utf-8", "ignore").decode("utf-8") if raw_url else None

DATABASES = {
    "default": dj_database_url.parse(
        clean_url,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}

# --------------------------------------------
# 🔐 Password Validation
# --------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------
# 🌐 Localization Settings
# --------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------
# 📦 Static and Media Files Configuration
# --------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --------------------------------------------
# 🧪 Miscellaneous Settings
# --------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------
# 👤 Custom User Model
# --------------------------------------------
AUTH_USER_MODEL = "users.User"

# --------------------------------------------
# 🚀 Django REST Framework (Session-Only)
# --------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# --------------------------------------------
# 🛡 Cookie & CSRF Settings for Session Auth
# --------------------------------------------
SESSION_COOKIE_SECURE   = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE      = True
CSRF_COOKIE_SAMESITE    = "None"

# --------------------------------------------
# 🔐 dj-rest-auth & allauth Settings
# --------------------------------------------
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_REQUIRED        = False
ACCOUNT_USERNAME_REQUIRED     = True
ACCOUNT_EMAIL_VERIFICATION    = "optional"

# After login, redirect to site root (middleware will forward to complete_profile)
LOGIN_REDIRECT_URL = "/"

# Automatically create a user on social login without showing the signup form
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "APP": {
            "client_id": os.getenv("DISCORD_CLIENT_ID"),
            "secret":    os.getenv("DISCORD_CLIENT_SECRET"),
            "key":       ""
        },
        "SCOPE": ["identify"],
        "AUTH_PARAMS": {"redirect_uri": os.getenv("DISCORD_REDIRECT_URI")},
    }
}

SOCIALACCOUNT_ADAPTER = "users.adapters.DiscordSocialAdapter"

# --------------------------------------------
# 🌐 CORS Configuration
# --------------------------------------------
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8001",
    "https://your-frontend-domain.com",
]

# --------------------------------------------
# 🚨 CSRF Trusted Origins
# --------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8001",
    "https://your-frontend-domain.com",
]

# --------------------------------------------
# 🚫 Disable all outgoing email (development)
# --------------------------------------------
# Don’t require or send any verification emails
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Drop all send_mail calls silently (no SMTP)
EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"
