"""
Django settings for ultrabackend project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables from .env file
load_dotenv()

# --------------------------------------------
# 📁 Base Directory Setup
# --------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------
# 🔐 Secret Key & Debug Mode
# --------------------------------------------

# Load secret key from environment for security
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# Set debug mode from env, default to False for safety
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# --------------------------------------------
# 🌍 Allowed Hosts

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "api.igoultra.de",
    ".herokuapp.com",
    "igoultra-backend-d20b10508b97.herokuapp.com",
]

# --------------------------------------------
# 🔑 Site Framework

SITE_ID = 1

# --------------------------------------------
# 🧩 Installed Applications

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # 3rd-party auth (Allauth + Discord)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.discord',

    # REST Auth integration
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # Useful dev/production tools
    'corsheaders',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',

    # Local apps
    'users',
    'xp',
    'seasons',
]

# --------------------------------------------
# 🧱 Middleware Stack

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Whitenoise for static file serving in production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------
# 🔗 URL and WSGI Settings

ROOT_URLCONF = 'ultrabackend.urls'
WSGI_APPLICATION = 'ultrabackend.wsgi.application'

# --------------------------------------------
# 🎨 Templates Configuration

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add custom template dirs here if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --------------------------------------------
# 🛢️ PostgreSQL Database Configuration

# Fix UnicodeDecodeError by cleaning URL if needed
raw_url = os.getenv("DATABASE_URL_LOCAL")
clean_url = raw_url.encode("utf-8", "ignore").decode("utf-8") if raw_url else None

DATABASES = {
    "default": dj_database_url.parse(
        clean_url,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}

# --------------------------------------------
# 🔐 Password Validation

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------
# 🌐 Localization Settings

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------------
# 📦 Static and Media Files Configuration

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --------------------------------------------
# 🧪 Miscellaneous Settings

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------
# 👤 Custom User Model

AUTH_USER_MODEL = "users.User"
