# Generated by Django 5.2 on 2025-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_type', 'tier', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='area_of_effect',
            field=models.PositiveIntegerField(blank=True, help_text='Radius der Wirkung in Metern (nur für aktive Skills)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='buff_type',
            field=models.CharField(blank=True, choices=[('resistance', 'Resistance'), ('shield', 'Shield'), ('aura', 'Aura'), ('regeneration', 'Regeneration'), ('damage_boost', 'Damage Boost'), ('speed_boost', 'Speed Boost'), ('critical_chance', 'Critical Chance'), ('armor', 'Armor'), ('evasion', 'Evasion'), ('healing', 'Healing')], help_text='Art des Buffs (nur für passive Skills)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='buff_value',
            field=models.CharField(blank=True, help_text="Buff-Wert z.B. '+10%', '+5', '2x' (nur für passive Skills)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='damage',
            field=models.PositiveIntegerField(blank=True, help_text='Schadenswert (nur für aktive Skills)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Dauer in Sekunden (nur für aktive Skills)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('stun', 'Stun'), ('burn', 'Burn'), ('slow', 'Slow'), ('heal', 'Heal'), ('damage', 'Damage'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('teleport', 'Teleport'), ('shield', 'Shield'), ('stealth', 'Stealth')], help_text='Art des Effekts (nur für aktive Skills)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='passive_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Dauer in Sekunden (nur für temporäre passive Skills)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='range',
            field=models.PositiveIntegerField(blank=True, help_text='Reichweite in Metern (nur für aktive Skills)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='active', help_text='Bestimmt ob der Skill aktiv oder passiv ist', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='trigger_condition',
            field=models.CharField(blank=True, choices=[('always_active', 'Always Active'), ('on_low_hp', 'On Low HP'), ('on_critical_hit', 'On Critical Hit'), ('on_damage_taken', 'On Damage Taken'), ('on_kill', 'On Kill'), ('on_heal', 'On Heal'), ('on_skill_use', 'On Skill Use'), ('on_block', 'On Block'), ('on_dodge', 'On Dodge'), ('on_combo', 'On Combo')], help_text='Aktivierungsbedingung (nur für passive Skills)', max_length=20, null=True),
        ),
    ]
