# Generated by Django 5.2 on 2025-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options_skill_area_of_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='damage',
            field=models.IntegerField(blank=True, help_text='Schadenswert (positiv für Schaden, negativ für Heilung, nur für aktive Skills)', null=True),
        ),
    ]
